import type { AnimationState } from "../core/types";
import manifest from "./character-dunmer-combat.animations.json";

/**
 * Runtime animation contract, generated by the asset pipeline
 * (elder-scrolls-asset-pipeline). The game references only SEMANTIC state names;
 * the mapping to any Bethesda source clip lives entirely in the pipeline. To
 * swap a clip (e.g. ROLL) you rebuild the GLB — no game-code change.
 */

export type RootMotionPolicy = "strip" | "consume";

export type ClipConfig = {
  looping: boolean;
  playbackRate: number;
  rootMotion: RootMotionPolicy;
  /** Source clip length in seconds, before playbackRate. */
  sourceDuration: number | null;
  /** Authored net root translation (metres, character space) or null. */
  rootMotionDelta: [number, number, number] | null;
  provenance: string;
};

type RigManifest = {
  rootBone: string;
  sockets: {
    rightHand: string;
    leftHand: string;
    weapon: string;
    weaponFallback: string;
    sheath: string;
  };
  recommendedScale: number;
  targetHeightMeters: number;
};

const RIG = manifest.rig as unknown as RigManifest;
const ANIMATIONS = manifest.animations as unknown as Record<string, ClipConfig>;

export const CHARACTER_GLB = "character-dunmer-combat.glb";

export const RIG_ROOT_BONE = RIG.rootBone;
export const RIG_SOCKETS = RIG.sockets;
export const CHARACTER_SCALE = RIG.recommendedScale;

const FALLBACK: ClipConfig = {
  looping: false,
  playbackRate: 1,
  rootMotion: "strip",
  sourceDuration: null,
  rootMotionDelta: null,
  provenance: "",
};

export function clipConfig(state: AnimationState): ClipConfig {
  return ANIMATIONS[state] ?? FALLBACK;
}

/**
 * Semantic states that represent free locomotion (mixer-driven, self-timed).
 * JUMP_START/JUMP_LAND are included even though they are one-shot combat-like
 * clips: they play while the player's `CombatAction` stays "idle" (jumping is
 * not a combat action), so the shared action clock keeps free-running instead
 * of resetting at takeoff/landing. Driving them externally from that stale
 * clock clamps them to their last frame from the very first rendered frame.
 * Self-timing avoids the stale clock entirely.
 */
export const LOCOMOTION_STATES: ReadonlySet<AnimationState> = new Set<AnimationState>([
  "IDLE",
  "SWORD_IDLE",
  "WALK",
  "WALK_BACK",
  "STRAFE_LEFT",
  "STRAFE_RIGHT",
  "RUN",
  "SPRINT",
  "GUARD",
  "JUMP_IDLE",
  "JUMP_START",
  "JUMP_LAND",
  "JUMP_LAND_LEFT",
  "JUMP_LAND_RIGHT",
]);

/** Every semantic state the built GLB is expected to contain. */
export const MANIFEST_STATES = Object.keys(ANIMATIONS) as AnimationState[];
