import roster from "./generated/races.json";

/**
 * The playable races.
 *
 * A race is a *body*: its own meshes, textures and skin tone, mounted on the
 * rig every character shares. That split is why adding a race costs under a
 * megabyte instead of duplicating the whole animation set, and why nothing in
 * combat, animation or inventory has to know which race is loaded.
 *
 * The roster is generated by the asset pipeline; this file only says what a
 * race means to the game.
 */

export type RaceId = string;

export type RaceDefinition = {
  id: RaceId;
  label: string;
  description: string;
  /** Race body GLB, relative to the deployment base URL. */
  asset: string;
  /** Content hash, used to bust a stale browser cache after a rebuild. */
  revision: string;
};

type BuiltRace = { label: string; description: string; asset: string; sha256: string };

const BUILT = roster.races as unknown as Record<string, BuiltRace>;

export const RACES: Readonly<Record<RaceId, RaceDefinition>> = Object.fromEntries(
  Object.entries(BUILT).map(([id, race]) => [id, {
    id,
    label: race.label,
    description: race.description,
    asset: race.asset,
    revision: race.sha256.slice(0, 16),
  }]),
);

/** Display order: the roster's, which is the order a player expects to read. */
export const RACE_IDS: readonly RaceId[] = Object.keys(RACES);

/** The rig every race is posed by. */
export const RIG_REVISION = roster.rig.sha256.slice(0, 16);

/**
 * The race the support envelopes and fitted hurtbox were measured from. Every
 * race shares the body, hands and feet meshes those measurements depend on, so
 * one set is correct for all of them.
 */
export const REFERENCE_RACE: RaceId = roster.referenceRace;

export const DEFAULT_RACE: RaceId = REFERENCE_RACE;

export function raceById(id: RaceId): RaceDefinition {
  const race = RACES[id];
  if (!race) throw new RangeError(`unknown race: ${id}`);
  return race;
}
